version: '3.0'

services:

  vpn:
    container_name: vpn
    image: test/openvpn 
    build: .
    privileged: true
    restart: unless-stopped
    ports:
      - "1194:1194/udp"
    volumes:
      - ovpn-data:/etc/openvpn
    networks:
      - net

volumes:
  ovpn-data:

networks:
  net: